package GUI;

/**
 *
 * @author abel
 */
public class CasillaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreCasilla = new javax.swing.JLabel();
        nombreCasilla_texto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        infoCasilla_texto = new javax.swing.JTextField();

        nombreCasilla.setText("Nombre");
        nombreCasilla.setEnabled(false);

        nombreCasilla_texto.setText("jTextField1");
        nombreCasilla_texto.setEnabled(false);
        nombreCasilla_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCasilla_textoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("CASILLA");

        infoCasilla_texto.setText("jTextField1");
        infoCasilla_texto.setEnabled(false);
        infoCasilla_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoCasilla_textoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(nombreCasilla)
                        .addGap(18, 18, 18)
                        .addComponent(nombreCasilla_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(infoCasilla_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCasilla)
                    .addComponent(nombreCasilla_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoCasilla_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreCasilla_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCasilla_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCasilla_textoActionPerformed

    private void infoCasilla_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoCasilla_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoCasilla_textoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField infoCasilla_texto;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nombreCasilla;
    private javax.swing.JTextField nombreCasilla_texto;
    // End of variables declaration//GEN-END:variables
}
