package GUI;

import civitas.Jugador;
import civitas.TituloPropiedad;
import java.util.ArrayList;

/**
 *
 * @author salva
 */
public class JugadorPanel extends javax.swing.JPanel {

    private Jugador jugador;

    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    public void setJugador(Jugador otro) {
        this.jugador = otro;
        texto_nombre.setText(jugador.getNombre());
        texto_saldo.setText(String.valueOf(jugador.getSaldo()));
        texto_encarcelado.setText((jugador.isEncarcelado()) ? "Sí" : "No");
        texto_especulador.setText((jugador.isEspeculador()) ? "Sí" : "No");
        this.repaint();
        this.rellenaPropiedades(jugador.getPropiedades());
        //this.validate(); // esto si añadimos/eliminamos algo
    }

    private void rellenaPropiedades(ArrayList<TituloPropiedad> lista) {
        // Se elimina la información antigua
        propiedades.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (TituloPropiedad t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
    }


/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_gui = new javax.swing.JLabel();
        texto_nombre = new javax.swing.JTextField();
        saldo_gui = new javax.swing.JLabel();
        encarcelado_gui = new javax.swing.JLabel();
        especulador_gui = new javax.swing.JLabel();
        texto_saldo = new javax.swing.JTextField();
        texto_encarcelado = new javax.swing.JTextField();
        texto_especulador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        propiedades = new javax.swing.JPanel();

        nombre_gui.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        nombre_gui.setText("Nombre");
        nombre_gui.setEnabled(false);

        texto_nombre.setText("jTextField1");
        texto_nombre.setEnabled(false);
        texto_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_nombreActionPerformed(evt);
            }
        });

        saldo_gui.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        saldo_gui.setText("Saldo");
        saldo_gui.setEnabled(false);

        encarcelado_gui.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        encarcelado_gui.setText("¿Está encarcelado?");
        encarcelado_gui.setEnabled(false);

        especulador_gui.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        especulador_gui.setText("¿Es especulador?");
        especulador_gui.setEnabled(false);

        texto_saldo.setText("jTextField2");
        texto_saldo.setEnabled(false);

        texto_encarcelado.setText("jTextField3");
        texto_encarcelado.setEnabled(false);

        texto_especulador.setText("jTextField4");
        texto_especulador.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        jLabel1.setText("Jugador Actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saldo_gui)
                            .addComponent(encarcelado_gui)
                            .addComponent(nombre_gui)
                            .addComponent(especulador_gui))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_encarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(texto_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_gui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldo_gui)
                    .addComponent(texto_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_encarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encarcelado_gui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especulador_gui)
                    .addComponent(texto_especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void texto_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel encarcelado_gui;
    private javax.swing.JLabel especulador_gui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre_gui;
    private javax.swing.JPanel propiedades;
    private javax.swing.JLabel saldo_gui;
    private javax.swing.JTextField texto_encarcelado;
    private javax.swing.JTextField texto_especulador;
    private javax.swing.JTextField texto_nombre;
    private javax.swing.JTextField texto_saldo;
    // End of variables declaration//GEN-END:variables
}
