package GUI;

import civitas.TituloPropiedad;

/**
 *
 * @author salva
 */
public class PropiedadPanel extends javax.swing.JPanel {

    private TituloPropiedad tituloPropiedad;
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    public void setPropiedad(TituloPropiedad otro){
        this.tituloPropiedad = otro;
        nombre_texto.setText(tituloPropiedad.getNombre());
        nCasas_texto.setText(String.valueOf(tituloPropiedad.getNumCasas()));
        nHoteles_texto.setText(String.valueOf(tituloPropiedad.getNumHoteles()));
        hipotecada_texto.setText((tituloPropiedad.getHipotecado()) ? "Sí" : "No");
        precioAlquiler_texto.setText(String.valueOf(tituloPropiedad.getPrecioAlquiler()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrePropiedad = new javax.swing.JLabel();
        nCasasPropiedad = new javax.swing.JLabel();
        nHotelesPropiedad = new javax.swing.JLabel();
        hipotecadaPropiedad = new javax.swing.JLabel();
        alquilerPropiedad = new javax.swing.JLabel();
        nombre_texto = new javax.swing.JTextField();
        nCasas_texto = new javax.swing.JTextField();
        nHoteles_texto = new javax.swing.JTextField();
        hipotecada_texto = new javax.swing.JTextField();
        precioAlquiler_texto = new javax.swing.JTextField();

        nombrePropiedad.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        nombrePropiedad.setText("Nombre:");
        nombrePropiedad.setEnabled(false);

        nCasasPropiedad.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        nCasasPropiedad.setText("Número de casas:");
        nCasasPropiedad.setEnabled(false);

        nHotelesPropiedad.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        nHotelesPropiedad.setText("Número de Hoteles:");
        nHotelesPropiedad.setEnabled(false);

        hipotecadaPropiedad.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        hipotecadaPropiedad.setText("¿Está hipotecada?:");
        hipotecadaPropiedad.setEnabled(false);

        alquilerPropiedad.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        alquilerPropiedad.setText("Precio de Alquiler:");
        alquilerPropiedad.setEnabled(false);

        nombre_texto.setText("jTextField1");
        nombre_texto.setEnabled(false);

        nCasas_texto.setText("jTextField2");
        nCasas_texto.setEnabled(false);

        nHoteles_texto.setText("jTextField3");
        nHoteles_texto.setEnabled(false);

        hipotecada_texto.setText("jTextField4");
        hipotecada_texto.setEnabled(false);

        precioAlquiler_texto.setText("jTextField5");
        precioAlquiler_texto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alquilerPropiedad)
                    .addComponent(hipotecadaPropiedad)
                    .addComponent(nHotelesPropiedad)
                    .addComponent(nCasasPropiedad)
                    .addComponent(nombrePropiedad))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nCasas_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nHoteles_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hipotecada_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioAlquiler_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePropiedad)
                    .addComponent(nombre_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nCasas_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nCasasPropiedad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nHoteles_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nHotelesPropiedad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hipotecadaPropiedad)
                    .addComponent(hipotecada_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioAlquiler_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alquilerPropiedad))
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alquilerPropiedad;
    private javax.swing.JLabel hipotecadaPropiedad;
    private javax.swing.JTextField hipotecada_texto;
    private javax.swing.JLabel nCasasPropiedad;
    private javax.swing.JTextField nCasas_texto;
    private javax.swing.JLabel nHotelesPropiedad;
    private javax.swing.JTextField nHoteles_texto;
    private javax.swing.JLabel nombrePropiedad;
    private javax.swing.JTextField nombre_texto;
    private javax.swing.JTextField precioAlquiler_texto;
    // End of variables declaration//GEN-END:variables
}
